// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowFile(arg1:string):Promise<void>;

export function AskPermission(arg1:string,arg2:string,arg3:number):Promise<boolean>;

export function Brodudp():Promise<void>;

export function Listentcp():Promise<void>;

export function RejectFile(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function Sendtcp(arg1:string,arg2:string):Promise<void>;
