// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowFile(arg1) {
  return window['go']['main']['App']['AllowFile'](arg1);
}

export function AskPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['AskPermission'](arg1, arg2, arg3);
}

export function Brodudp() {
  return window['go']['main']['App']['Brodudp']();
}

export function Listentcp() {
  return window['go']['main']['App']['Listentcp']();
}

export function RejectFile(arg1) {
  return window['go']['main']['App']['RejectFile'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function Sendtcp(arg1, arg2) {
  return window['go']['main']['App']['Sendtcp'](arg1, arg2);
}
